Repository jenkinsci/jenkins-cloudformation-plugin, pull requests merged in 2022-11, with the labels that each got.

#58 Fix CVE-2019-1003061 Secrets stored in plain text
  README.md
  docs/images/credentials_binding.png
  docs/images/env_vars.png
  src/main/java/com/syncapse/jenkinsci/plugins/awscloudformationwrapper/PostBuildStackBean.java
  src/main/java/com/syncapse/jenkinsci/plugins/awscloudformationwrapper/SimpleStackBean.java
  src/main/java/com/syncapse/jenkinsci/plugins/awscloudformationwrapper/StackBean.java
  src/test/java/com/syncapse/jenkinsci/plugins/awscloudformationwrapper/CloudFormationBuildWrapperTest.java
  src/test/java/com/syncapse/jenkinsci/plugins/awscloudformationwrapper/StackBeanTest.java
Labels: fix

#60 Convert to fully automated versioning
  pom.xml
Labels: chore

#61 Update name to CloudFormation plugin
  pom.xml
Labels: chore

#41 Added all new regions. Removed private as redundant in Enum
  src/main/java/com/syncapse/jenkinsci/plugins/awscloudformationwrapper/Region.java
Labels: feature
